6) Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on
the given dataset.

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score



In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [6]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
iris_df.shape

(150, 5)

In [11]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [12]:
iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [14]:
x = iris_df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y = iris_df['target']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
# Train Naïve Bayes classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

GaussianNB()

In [18]:
print("Train Score : ",nb_model.score(X_train, y_train)*100,"%")

Train Score :  95.0 %


In [19]:
y_pred = nb_model.predict(X_test)

In [21]:
print("y_pred Data :- ",y_pred)

y_pred Data :-  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [23]:
print("y_test Data :- ",y_test.values)

y_test Data :-  [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [24]:
print("Test Score : ",nb_model.score(X_test, y_test)*100,"%")

Test Score :  100.0 %


In [26]:
print("Cpnfusion Matrix :- ")
print(confusion_matrix(y_test, y_pred))
confusion_matrix = confusion_matrix(y_test, y_pred)

Cpnfusion Matrix :- 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [29]:
print("Accuracy : ",accuracy_score(y_test, y_pred)*100,"%")

Accuracy :  100.0 %


In [30]:
print("Precision : ",precision_score(y_test, y_pred, average='macro')*100,"%")

Precision :  100.0 %


In [31]:
print("Recall : ",recall_score(y_test, y_pred, average='macro')*100,"%")

Recall :  100.0 %


In [32]:
print("Error Rate : ",(1-accuracy_score(y_test, y_pred))*100,"%")

Error Rate :  0.0 %
